site_name: OpenShift Documentation
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/images/redhat.svg
  favicon: assets/redhat-favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
repo_url: https://github.com/aireilly/openshift-docs
repo_name: openshift-mkdocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - admonition
  - attr_list
  - md_in_html













